/*
 * This source file was generated by the Gradle 'init' task
 */
package simplecalculator;

import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner sc=new Scanner(System.in);
        List<Operation> ops=List.of(
            new AddOperation(),
            new SubOperation(),
            new MulOperation(),
            new DivOperation()
        );
        Calculator cal=new Calculator(ops);
        while (true) {
            System.out.println("Enter operation and two numers(or typ EXIT)");
            String input=sc.nextLine();

            if(input.equalsIgnoreCase("exit")) break;
            String[] parts=input.split(" ");

            if(parts.length<3)
            {
                System.out.println("Invalid input format");
                continue;
            }

            String op=parts[0];
            int a=Integer.parseInt(parts[1]);
            int b=Integer.parseInt(parts[2]);

            try{
                int result=cal.calculate(op, a, b);
                System.out.println("Result : "+result);
            }catch(Exception e)
            {
                System.out.println("Error : "+e.getMessage());
            }
        }
        sc.close();
    }
}
